[window]
dimensions = { columns = 150, lines = 50}
opacity = 0.98

[font]
size = 12
normal = {family = "Liberation Mono", style = "Regular"}
italic = {family = "Liberation Mono", style = "Regular"}
bold   = {family = "Liberation Mono", style = "Regular"}
bold_italic = {family = "Liberation Mono", style = "Regular"}
